### ISSUE TITLE
Menu background scaling issue

### ISSUE THREAD

**Issue by blakegearin** [OT-Archmage/SteamDeckCustomisations#2]
![image](https://user-images.githubusercontent.com/17950836/214019806-642c744c-3570-4f81-a095-7d1e5e01ec50.png)

When using the [official Steam Deck dock](https://www.steamdeck.com/en/dock) with my TV the [menu background image](https://github.com/OT-Archmage/SteamDeckCustomisations/blob/main/CSS%20Themes/Wii%20Theme/MenuBackground.png) of your Wii Theme seemed to not scale properly.

I followed the [CEF Debugger instructions](https://docs.deckthemes.com/#/CSSLoader/Cef_Debugger?id=%f0%9f%a7%b0-recommended-setup) from DeckThemes to look into this. I found that changing [this line](https://github.com/OT-Archmage/SteamDeckCustomisations/blob/main/CSS%20Themes/Wii%20Theme/shared.css#L155) to `background-size: cover;` fixes the issue. 

The `cover` value is already set [elsewhere](https://github.com/OT-Archmage/SteamDeckCustomisations/blob/main/CSS%20Themes/Wii%20Theme/shared.css#L36) which is likely why the [tab border image](https://github.com/OT-Archmage/SteamDeckCustomisations/blob/main/CSS%20Themes/Wii%20Theme/TabBorder.png) wasn't having this issue. Here's [some documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size#values) on the values `background-size` accepts.

I also unplugged my Steam Deck from my dock to make sure this change didn't mess up the image scale on the built-in screen. I didn't notice a difference.

**Comment by OT-Archmage** [comment]
Thanks for bringing this to my attention, I haven't used my deck docked so this slipped through the cracks!
I've pushed the change you suggested and it'll be updated on the Theme store once it goes through verification.
